fix(build-time-tests): read variable before assignment
When building the previous commit the build-time test failed.
During handling of a CalledProcessError that occured when running the
demo hello world app. The error handling acceses a variable that was not
assigned yet. See detailed error logs below.

This commit fixes this error. Note: All dotnet8 builds failed during
running the hello world demo app, so there is most likely another error
that needs to be resolved. Fixing the error handling may allow to see
the underlying issue.

```
DEBUG: Full Context:
- TestDirectory: /tmp/tmp1re_r8um
- SourcePackageRoot: /<<PKGBUILDDIR>>
- DotnetBuiltArtifactsBasePath: /<<PKGBUILDDIR>>/artifacts/x64/Release
- DotnetRoot: /tmp/tmp1re_r8um/dotnet
- NuGetPackagesDirectory: /tmp/tmp1re_r8um/packages
- FakeHome: /tmp/tmp1re_r8um/home
- TestProjectDirectory: /tmp/tmp1re_r8um/test-project
- TestProjectName: hello
- TestProjectFile: /tmp/tmp1re_r8um/test-project/hello.csproj
- UbuntuVersion: 25.04
- DotnetSdkVersion: 8.0.111
- DotnetRuntimeVersion: 8.0.11
- DotnetRuntimeIdentifier: ubuntu.25.04-x64
- DotnetArchitecture: x64

…

DEBUG: Executing: ['/tmp/tmp2ccqg_s4/dotnet/dotnet', '/tmp/tmp2ccqg_s4/test-project/bin/Debug/net9.0/hello.dll']
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/./debian/tests/build-time-tests/tests.py", line 387, in __RunDotnet
    output = subprocess.check_output(cwd=self.TestDirectory,
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/tmp/tmp2ccqg_s4/dotnet/dotnet', '/tmp/tmp2ccqg_s4/test-project/bin/Debug/net9.0/hello.dll']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/./debian/tests/build-time-tests/tests.py", line 548, in <module>
    testContext.RunTests()
  File "/<<PKGBUILDDIR>>/./debian/tests/build-time-tests/tests.py", line 271, in RunTests
    output = self.__RunDotnet([dllPath])
  File "/<<PKGBUILDDIR>>/./debian/tests/build-time-tests/tests.py", line 394, in __RunDotnet
    f"- Output:\n{output}")
UnboundLocalError: local variable 'output' referenced before assignment
```

Signed-off-by: Dominik Viererbe <dominik.viererbe@canonical.com>