fix: failure finding SDK artifacts
.NET 10 introduced a chanage where the SDK built artifacts tarball
is placed. There no longer exists a symlink at:
`artifacts/assets/Release/dotnet-sdk-*.tar.gz`

For reference, this is an error caused by this change:

```text
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/./debian/tests/build-time-tests/tests.py", line 549, in <module>
    testContext.RunTests()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/<<PKGBUILDDIR>>/./debian/tests/build-time-tests/tests.py", line 257, in RunTests
    self.__ExtractSdk()
    ~~~~~~~~~~~~~~~~~^^
  File "/<<PKGBUILDDIR>>/./debian/tests/build-time-tests/tests.py", line 325, in __ExtractSdk
    tarPath=GetSourceBuiltArtifactsTarball(
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        basePath=self.DotnetBuiltArtifactsBasePath,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        sdkVersion=self.DotnetSdkVersion,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        type="SDK"),
        ^^^^^^^^^^^
  File "/<<PKGBUILDDIR>>/debian/eng/source_build_artifact_path.py", line 31, in GetSourceBuiltArtifactsTarball
    raise ValueError(f"Source built artifacts tarball not found "
                     f"(glob pattern: '{globPattern}').")
ValueError: Source built artifacts tarball not found (glob pattern: '/<<PKGBUILDDIR>>/artifacts/assets/Release/dotnet-sdk-10.0.100-preview.5*-*.tar.gz').
```

Signed-off-by: Dominik Viererbe <dominik.viererbe@canonical.com>